name = "mavis2103/stdlib"
version = "main"
compiler = "v1.1.19"
plutus = "v3.0.1"
description = "The Aiken Standard Library"

[repository]
user = "mavis2103"
project = "stdlib"
platform = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "v2.1.1"
source = "github"
